---
version: 2

# ServerName for standalone servers (Bukkit, Fabric, or Forge)
# Proxies will use the server names defined in the config
server:
  name: "serverName"
  # Weather the plugin is running in a proxy network
  # Set this to true on both ends to enable plugin messaging for some events (player advancements, death messages, etc.)
  usingProxy: false
  # Weather global chat should be the default chat channel for players
  globalChatEnabledByDefault: false

# Discord bot configuration
# You only need one of these per server network, assuming you're running a primary proxy/socket to handle chats
# If you're running a standalone server, or this is the main server/proxy in your network, set primary to true and set the channel mappings accordingly
discord:
  enabled: true
  token: ""
  inviteUrl: "&6Join our Discord: &ahttps://discord.gg/yourInvite"

  # Server to Discord Channel mapping
  channels:
    # in the format of serverName: guildID/channelId
    global: "123456789012345678/123456789012345678"
    serverName: "123456789012345678/123456789012345678"

# Formatting for server messages
formatting:
  # Whether TaterComms should handle chat formatting
  enabled: false
  # Allow specific servers to bypass chat formatting
  # The backend server will handle all the chat formatting
  passthrough:
    - example1
    - example2
  chat:
    # Common placeholders for player events/messages:
    #   %player% - Player name
    #   %displayname% - Player display name
    #   %message% - Message
    #   %server% - Server name
    #   %prefix% - Player prefix
    #   %suffix% - Player suffix

    # Player advancement messages
    #   %advancement% - Advancement name
    advancement: "%displayname% has made the advancement [%advancement%]"
    # Player death messages
    #   %deathmessage% - Death message
    death: "%deathmessage%"
    # Player login messages
    login: "%displayname% joined the game"
    # Player logout messages
    logout: "%displayname% left the game"

    # Server start message
    serverStarted: "**Server Started**"
    # Server stop message
    serverStopped: "**Server Stopped**"

    # Formatting for messages coming from Discord
    discord: "&9[D]&r %displayname% >> %message%"

    # Message formatting for each type of chat
    #   %message% - Message
    # Global chat formatting
    global: "&a[G]&r %displayname% >> %message%"
    # Local chat formatting
    local: "&e[L]&r %displayname% >> %message%"
    # Remote chat formatting
    remote: "&4[%server%]&r %displayname% >> %message%"

# Remote TCP socket configuration (for servers that you can't run behind a proxy)
# Fun fact: if you're having issues running Forge 1.13+ behind a proxy, check out Ambassador: https://github.com/adde0109/Ambassador
# Short explanation: The 1.13 update changed the way that Forge initializes and syncs mod/datapack data with the server, this causes issues with the way that the proxy works
remote:
  enabled: false
  primary: false
  host: 127.0.0.1
  port: 5483
  secret: ""
